Feature/tao 6176/import eligibilities
oat-sa/extension-tao-testcenter pull request #62
Opened 2018-04-27 09:44 UTC by ionutpad

2018-04-27 12:41 UTC, siwane requested changes

2018-04-27 12:41 UTC, siwane commented on scripts/update/Updater.php
> +            $this->setVersion('3.12.0');
Should output 3.11.0

2018-05-03 15:14 UTC, SergiiTao commented on controller/TestCenterManager.php
> +        $data['report'] = $report;
if `empy($files)` `$report` is undefined

2018-05-03 15:16 UTC, SergiiTao commented on controller/TestCenterManager.php
> +        foreach ($files as $file){
are you sure that $files is an array?

2018-05-04 07:16 UTC, SergiiTao commented on controller/TestCenterManager.php
> +        if(isset($schema[ImportMapper::OPTION_SCHEMA_MANDATORY])){
if (!isset(...

2018-05-04 07:22 UTC, SergiiTao commented on controller/TestCenterManager.php
> +     * @throws \oat\oatbox\service\exception\InvalidServiceManagerException
Please add @return tag

2018-05-04 07:24 UTC, SergiiTao commented on controller/TestCenterManager.php
> +            if (TestCenterService::CLASS_URI === $class){
and what if not? seems it is possible that function will return null in this case

2018-05-04 11:59 UTC, SergiiTao requested changes

2018-05-04 11:59 UTC, SergiiTao commented on model/import/RdsEligibilityImportService.php
> +        $created = false;
Unused variable

2018-05-04 11:59 UTC, SergiiTao commented on model/import/RdsEligibilityImportService.php
> +        $eligibility = current($eligibility);
One row ago `$eligibility` was an array and now an item of this array.
Please don't use one name for diffrerent objects. It is difficult to debug

2018-05-04 11:59 UTC, SergiiTao commented on model/import/RdsEligibilityImportService.php
> +        $eligibility = current($eligibility);
what is current element? [0]  or this array was iterated somewhere? Please use [0] if you want the first item

2018-05-04 11:59 UTC, SergiiTao commented on model/import/RdsEligibilityImportService.php
> +     * @return mixed
@return `core_kernel_classes_Resource` ?

2018-05-08 14:36 UTC, SergiiTao approved these changes

2018-05-16 12:47 UTC, merged